variables:
  - name: "AZURECONTAINERREGISTRY"
    description: "the Azure container registry name"
  - name: "CONTAINERNAME"
    description: "the container image name"
  - name: "RESOURCEGROUP"
    description: "the Azure resource group of your AKS cluster"
  - name: "CLUSTERNAME"
    description: "the AKS cluster name"
  - name: "BRANCHNAME"
    description: "the Github branch to automatically deploy from"
  - name: "BUILDCONTEXTPATH"
    description: "the path to the Docker build context"
  - name: "MANIFESTPATH"
    description: "the path to the manifest files or helm charts"
variableDefaults:
  - name: "CHARTPATH"
    value: "./charts"
    disablePrompt: true
  - name: "CHARTOVERRIDEPATH"
    value: "./charts/production.yaml"
    disablePrompt: true
  - name: "BUILDCONTEXTPATH"
    value: "."